-- Run this migration in the Supabase SQL Editor for the Replacement page.

create table if not exists public.inventory_adjustments (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  reason text not null,
  payment_method text,
  employee_id uuid references auth.users(id) on delete set null,
  employee_name text,
  sale_id bigint references public.sales(id) on delete set null,
  source_adjustment_id bigint references public.inventory_adjustments(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.inventory_adjustments add column if not exists employee_id uuid references auth.users(id) on delete set null;
alter table public.inventory_adjustments add column if not exists employee_name text;
alter table public.inventory_adjustments add column if not exists sale_id bigint references public.sales(id) on delete set null;
alter table public.inventory_adjustments add column if not exists source_adjustment_id bigint references public.inventory_adjustments(id) on delete set null;
alter table public.inventory_adjustments add column if not exists payment_method text;
create index if not exists idx_inventory_adjustments_created_at on public.inventory_adjustments(created_at desc);
create index if not exists idx_inventory_adjustments_source_adjustment_id on public.inventory_adjustments(source_adjustment_id);

alter table public.inventory_adjustments enable row level security;
revoke all on table public.inventory_adjustments from anon;
grant select, insert on table public.inventory_adjustments to authenticated;

drop policy if exists "Staff can view inventory adjustments" on public.inventory_adjustments;
drop policy if exists "Employees can create replacements" on public.inventory_adjustments;

create policy "Staff can view inventory adjustments"
  on public.inventory_adjustments for select to authenticated
  using (employee_id = auth.uid() or exists (select 1 from public.profiles where id = auth.uid() and role = 'owner'));

create policy "Employees can create replacements"
  on public.inventory_adjustments for insert to authenticated
  with check (employee_id = auth.uid() and exists (select 1 from public.profiles where id = auth.uid() and role = 'employee'));
