-- Vape shop POS schema for Supabase
-- Run this in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  role text not null default 'pending' check (role in ('owner', 'employee', 'pending')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  image text,
  name text not null,
  flavor text,
  category text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  status text not null default 'Active' check (status in ('Active', 'Low Stock', 'Out of Stock')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  flavor text,
  category text,
  quantity integer not null default 1,
  total_amount numeric(12,2) not null default 0,
  employee_id uuid references auth.users(id) on delete set null,
  employee_name text,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_stock on public.products(stock);
create index if not exists idx_sales_created_at on public.sales(created_at desc);
create index if not exists idx_sales_employee_id on public.sales(employee_id);

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.update_updated_at_column();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row
execute function public.update_updated_at_column();

alter table public.profiles disable row level security;
alter table public.products disable row level security;
alter table public.sales disable row level security;
