-- Run this in the Supabase SQL Editor after creating your Supabase project.
-- Create each user's email/password under Authentication > Users, then add
-- their matching Auth user ID to public.profiles with role owner or employee.
-- After creating both Auth users, you can assign both roles with one statement:
-- insert into public.profiles (id, role, display_name) values
--   ('OWNER_AUTH_USER_UUID', 'owner', 'Shop Owner'),
--   ('EMPLOYEE_AUTH_USER_UUID', 'employee', 'Employee');

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  flavor text,
  category text not null,
  price numeric(10, 2) not null default 0,
  stock integer not null default 0,
  image text,
  status text not null default 'Active',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

alter table public.products add column if not exists flavor text;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  role text not null default 'pending' check (role in ('owner', 'employee', 'pending')),
  display_name text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
revoke all on table public.profiles from anon, authenticated;
grant select on table public.profiles to authenticated;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id);

-- The browser app uses Supabase Auth, so product access is limited to signed-in
-- accounts with an assigned owner or employee profile.
alter table public.products enable row level security;
revoke all on table public.products from anon;
grant select, insert, update, delete on table public.products to authenticated;

drop policy if exists "Products are viewable" on public.products;
drop policy if exists "Products can be added" on public.products;
drop policy if exists "Products can be updated" on public.products;
drop policy if exists "Products can be deleted" on public.products;

create policy "Assigned staff can view products"
  on public.products for select to authenticated
  using (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role in ('owner', 'employee')
    )
  );

create policy "Assigned staff can add products"
  on public.products for insert to authenticated
  with check (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role in ('owner', 'employee')
    )
  );

create policy "Assigned staff can update products"
  on public.products for update to authenticated
  using (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role in ('owner', 'employee')
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role in ('owner', 'employee')
    )
  );

create policy "Assigned staff can delete products"
  on public.products for delete to authenticated
  using (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role in ('owner', 'employee')
    )
  );
